FROM node:20-alpine

WORKDIR /app

COPY nginx.conf /etc/nginx/nginx.conf

COPY Frontend/package.json Frontend/package-lock.json ./

RUN npm ci

COPY Frontend/ .

RUN npm run build

EXPOSE 3000
CMD ["node", "build"]